export const FETCH_LOCATION_START = 'FETCH_LOCATION_START';
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_FAILED = 'FETCH_LOCATION_FAILED';

export const FETCH_CATEGORY_START = 'FETCH_CATEGORY_START';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';

export const SET_CATEGORY = 'SET_CATEGORY';
export const SUBCATEGORY_START = 'SUBCATEGORY_START';
export const SET_LOCATION = 'SET_LOCATION';

export const START_MENU_QUERY = 'START_MENU_QUERY';
export const SET_MENU = 'SET_MENU';

export const TOGGLE_MAP = 'TOGGLE_MAP';

export const GET_ALL_LOCATIONS = 'GET_ALL_LOCATIONS';
export const GET_NEW_LOCATIONS = 'GET_NEW_LOCATIONS';
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';


export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';